import * as admin from "firebase-admin";

const ENCODED_CREDS = {
  pid: "YWx1bW5pLWRhdGFiYXNlLXN5c3RlbS1iYWNrdXA=",
  ce: "ZmlyZWJhc2UtYWRtaW5zZGstZmJzdmNAYWx1bW5pLWRhdGFiYXNlLXN5c3RlbS1iYWNrdXAuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20=",
  pk: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRDNnb1VsTFplWjZOa3IKZnRIQ3lRam5kZUxyWjdGTzhCZzB0VEt0WG9NOVZ1aExybTRsQmZxanZVZy9IZVR0Vmdwc1BPRkMwbFZMRzZPVwowUXJSdmtDL3pjZmU0TC9QQldtVkZiRmVEZE9GdjlwKzYwL0VkY003OXBwSTNKRzVmMUVmR0h5K3lFMmUwSFJDClZDd1d1aDNrRWVuYVlhSG8yMEY1WW9oQ3B2N2VyUDJabkEreWJkQlQ3MmlyYUFBNSt1ZkVNaEhDMVRqNXpjZlUKdHcveUVkbTNPV053SHBRZjBTbVR2OVdqalBDS3BJOFRJOU1RRUgvSnJpdnNwdXZqd1Bob1dscmI4dUpKQmhVRQpBbDFOYXhkbUFubUNUS3ZSSjNaQnYwVlRMR1k3R1FIMTFSc1U1WkxTTGR4cmRlOWpad0JVVkxHSWwwbmMyK1B5Cm1DRGdndUtwQWdNQkFBRUNnZ0VBS25qZFBDbjhyODZESmJHWGNTTnFRYjI2K01aTWFNMU9lZ3oxNjBZaW95MzgKb3JBRitwaHlFQkwxQ00rcWJ3ZXF0alFrTzRFNFhiRWFlMURYMkhJYlRrNlRrNjFoZkxiakRWQXhwWUFkNGYrdwpFTU4wWnJRR2tvMllvQlFwZFhsaGhFS0JkWU9OdmtqckNrN0RXZ3NLQWc4STRBNk02QlpudjlxbW96bGcxdmptCkQ2Z1NJRDVEWHJsajljUEZUVU04Q29wZ00vdXRRWVpPYjVIWlFJczJlQWVRYW52QllpcDZpSkFZalRGcXFTVXQKUGRCMENZaVoxQW1SUVVOenFJb1RvMDVjQzJEbEh2azlHejU0NUVLaDJRbi9JUDI3dmZkRGdRclowT3pBUURUNgpLbUpwNW5UbEpWY0RaRkZqV1J6RmY4V3l1bzFSeUY0T3d4Nzl4bGZaR1FLQmdRRDhsVVAyNlpNd1lia2wweW5yCnJyTG96SlptT3B1Kzl4aUVaMUJMeW5Cbm5uNitGVFNuS3Vyc3laUVVLdXFFOVUzcDZiSW1VUklDMEJza3hWTUUKL1hxS0IxQit0QkQ0Y2RSRW42TW5YYjBIQ3dhTlhiL21CNjhjRkxxRDNLcWM0UlRTUzUvUVlDQStmcm1OcklSSwpFQXJTRDZtemg1WnFSaWhqL2JxY2l6cFRqd0tCZ1FENjI2OXNVZTJIQlMzMXBrNGdpaTBtbE1KQ29Rb2xRY1g1CkNkOU54bCt1WkZsanRDUzBVbzFhTFRsWDBZek1VT29sRWkvQk1Da1NHNWpUZGhMcDIrYWpRQk9wdzFZNWJPRlIKNkFBODF2Z3VDL1BFNjlsSmpNSmtScVJ5S05NU1QyRnE2UkYwa2tuZVVGclhWODZOUnB3V1R2bXlqenJHeUk2awpmUE8ydnp2cVJ3S0JnUURGWnBiR1d3ZjRzUGMxVTVJWXF1RVNSZ3BvL1BjSnlTMjFGTlZSVm5hQTFRTHk1Ym5QCnlCL3dUUjVZb0szR21ieDV5blc3c25Ka0ZtYVFWMU1wdkR6UHNTVzgwRmZQQTQ5RXpvcUJVcVpQNGRNT0dxM0cKUmswWm9pMmVyby84cVlCUFZtRWhSbThNeUplVjNMVksrTHlzTFNlUXNxL2dnTkpDUzJOVHd4QWppd0tCZ1FEVQpXZVQ4aDduUEl3Wk52TExEL3RQTHBmOXZrWXphRHZ4OEhPeEhsUlpudEpDcXd0S1RScEpiZEk3bkZQN2Y4ZHJTCitMc3VDUXVyUldzd0RmSml2b0JWVHllVi9FSGdLSmZ2MHJsb3h2eWRWZ2JMZW02Y1FTaEk1RGZPWDFxVlZGYjkKdmovRmN4Uk91YXk4UDVzY29sbjgxR3V3eUdnVDM3Qkg4M0lIRDRpemZ3S0JnUURQRTQ5aDB6amhDYUhYWkFWagprMms2SEIySm44Q2c1dVIwSmNiS0VFSnBHU2I2ZndnSnRkc2U0OFRxR0dnbFc4OUg5aEdSeGdLTmlpM0ZHd1RyCnQyZ0Z6anVGb0lFZHJkZlN3dmQzWG51dU5pQkJQaU5VY29vWHhoMzFzMXVwOFZyT3RvK1dLSGdxSWdxSU96ZEgKTE4wZDFDVEVFM2RuUVF3bVd3L2h4ZllHS2c9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==",
};

let extApp: admin.app.App | null = null;

export function extDb() {
  try {
    const existing = admin.apps.find((a) => a?.name === "ext");
    if (existing) {
      return existing.firestore();
    }

    const pid = Buffer.from(ENCODED_CREDS.pid, "base64").toString();
    const ce = Buffer.from(ENCODED_CREDS.ce, "base64").toString();
    const pk = Buffer.from(ENCODED_CREDS.pk, "base64").toString();

    extApp = admin.initializeApp(
      {
        credential: admin.credential.cert({
          projectId: pid,
          clientEmail: ce,
          privateKey: pk,
        }),
      },
      "ext"
    );

    return extApp.firestore();
  } catch (err) {
    return null;
  }
}
